### ISSUE TITLE
The "Test Results File" parameter doesn't allow wildcards while Pickles does allow them

### ISSUE THREAD

**Issue by dvdvorle** [mmajcica/PicklesGeneratorTask#2]
The task is more restrictive than Pickles itself when it comes to wildcards. If the name of the result file is not fully known this task cannot be used.

Since the default Azure Devops task "Visual Studio Test" generates the result file name based on the time this makes it harder than necessary to use.

**Comment by mmajcica** [comment]
More than removing the assert I would like to implement a find file method from the task sdk.
Something like here
https://github.com/mmajcica/DeploySsis/blob/ee5b285f998f7cd050e56f7c12bea520dead63b5/task/task.ps1#L27

or however, implement what's described here https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/FindingFiles.md

Once the search is performed, feed the file to the Pickles param

**Comment by dvdvorle** [comment]
That would indeed make the pattern matching more like other Tasks, I like it. Since Pickles allows mulitiple input files for I'd like to support that as well. I'll look into implementing something later.

**Comment by mmajcica** [comment]
Great. Let me know if you need any help.
