### ISSUE TITLE
The "Output Directory" parameter should allow non-existing directories

### ISSUE THREAD

**Issue by dvdvorle** [mmajcica/PicklesGeneratorTask#3]
Pickles will create the directory when it doesn't exist. The current implementation of this task makes it so that I have to create the output directory myself. I'd like the task to allow non-existing directory for this parameter.

**Comment by mmajcica** [comment]
I'm a bit lost, in the code I do check if the given output folder is created. Is maybe this line throwing an exception in that case?

https://github.com/mmajcica/PicklesGeneratorTask/blob/9f8f2a4e6ca9c909381ee447d0bd5c24560b8c91/task/task.ps1#L25

**Comment by dvdvorle** [comment]
Yes that's the line that throws, but Pickles will create the directory if needed anyway, so there's no need to create it yourself.
